openapi: 3.1.0
info:
  title: Request Bodies for OpenSearch Query Datasources API
  description: Request Bodies for OpenSearch Query Datasources API
  version: 1.0.0
paths: {}
components:
  schemas:
    DataSource:
      type: object
      properties:
        name:
          type: string
        connector:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
      required:
        - name
        - connector
        - properties
    DataSourceList:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
          connector:
            type: string
          allowedRoles:
            type: array
            items:
              type: string
          properties:
            type: object
            additionalProperties:
              type: string
          resultIndex:
            type: string
          status:
            type: string
    DataSourceRetrieve:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        connector:
          type: string
        allowedRoles:
          type: array
          items:
            type: string
        properties:
          type: object
          additionalProperties:
            type: string
        resultIndex:
          type: string
        status:
          type: string
    DataSourceNotFound:
      type: object
      properties:
        status:
          type: integer
        error:
          type: object
          properties:
            type:
              type: string
            reason:
              type: string
            details:
              type: string
